project:
  type: website
  output-dir: docs

website:
  title: "RidgeMake"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Reference"
        href: reference/index.qmd

format:
  html:
    theme: cosmo
    toc: true

quartodoc:
  package: ridge_remake
  dir: reference
  sections:
    - title: "Main API"
      contents:
        - ridge_remake.get_reg_line.get_reg_line
        - ridge_remake.ridge_scatter.ridge_scatter
        - ridge_remake.ridge_scatter_line.ridge_scatter_line
        - ridge_remake.ridge_r2.ridge_get_r2

