project:
  type: website
  output-dir: docs

website:
  title: "RidgeMake"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Reference"
        href: reference/index.qmd
      - text: "Tutorial"
        href: tutorial.qmd
      - text: "Discussion"
        href: discussion.qmd

format:
  html:
    theme: cosmo
    toc: true

quartodoc:
  package: ridge_remake
  dir: reference
  sections:
    - title: "Main API"
      desc: "Core functions for fitting and visualizing a simple linear regression."
      contents:
        - get_reg_line
        - ridge_scatter
        - ridge_scatter_line
        - ridge_r2
