name: group-24-524
channels:
  - conda-forge
dependencies:
  - pytest
  - python=3.12
  - numpy<2
  - pandas
  - copier
  - hatch
  - hatchling
  - quartodoc
  - matplotlib
  - pip
  - pip:
      - quartodoc

